### ISSUE TITLE
Funktionsskript 1

### ISSUE THREAD

**Issue by JuliaKeiter** [Ketii/GruppenarbeitWA2021#1]
Welche Funktionen wollen wir erstellen?

**Comment by DanuschaGrosse-Hering** [comment]
Mit kategorialen Variablen sind noch nominale Merkmale wie hier "Studiengang" gemeint oder ?

**Comment by Ketii** [comment]
Ja, auch Mathe LK ist kategorial.

**Comment by Ketii** [comment]
Ja, Mathe LK ist auch eine kategoriale Variable, insgesamt haben wir 4 kategoriale Variablen.

**Comment by Ketii** [comment]
Wollen wir vielleicht die verschiedenen Kovarianzen noch miteinander vergleichen?

**Comment by JuliaKeiter** [comment]
Wollen wir die Varianz für die Funktion in a) nehmen?

**Comment by JuliaKeiter** [comment]
meinst du dann welche größer und kleiner ist oder wie?

**Comment by Ketii** [comment]
> Wollen wir die Varianz für die Funktion in a) nehmen?

Ich glaube das ist nicht mehr notwendig wenn  wir die Standardabweichung betrachten.

**Comment by JuliaKeiter** [comment]
okay

**Comment by Ketii** [comment]
> meinst du dann welche größer und kleiner ist oder wie?

Ja und wenn die unterschiedlich sind können wir noch überlegen warum

**Comment by Ketii** [comment]
> Wollen wir vielleicht die verschiedenen Kovarianzen noch miteinander vergleichen?
Für Teilaufgabe 3. c) sollten wir aber eher nominale Zusammenhangsmaße anwenden, wie z.B Chi-Quadrat oder Phi-Koeffizient meint ihr nicht?

**Comment by JuliaKeiter** [comment]
doch stimmt schon, aber es ist voll schwierig alle Koeffizienten für den Chi-Quadrat Koeffizienten zu bestimmen. Hast du eine Idee wie das gehen könnte?

> Wollen wir vielleicht die verschiedenen Kovarianzen noch miteinander vergleichen?
> Für Teilaufgabe 3. c) sollten wir aber eher nominale Zusammenhangsmaße anwenden, wie z.B Chi-Quadrat oder Phi-Koeffizient meint ihr nicht?

**Comment by Kaya0110** [comment]
Für Aufgabenteil e lohnt es sich nicht einen Teil noch intern zu definieren oder?

**Comment by JuliaKeiter** [comment]
das einzige, was vielleicht nicht ganz selbstverständlich ist, ist meiner Meinung nach die quantil() Funktion, aber ich hab keine Ahnung wie man sowas von Hand machen würde

> Für Aufgabenteil e lohnt es sich nicht einen Teil noch intern zu definieren oder?

**Comment by Kaya0110** [comment]
Daran hätte ich jetzt auch am ehesten gedacht, ich schaue mal nach ob man das noch sinnvoll definieren kann...

**Comment by Ketii** [comment]
> doch stimmt schon, aber es ist voll schwierig alle Koeffizienten für den Chi-Quadrat Koeffizienten zu bestimmen. Hast du eine Idee wie das gehen könnte?
> 
> > Wollen wir vielleicht die verschiedenen Kovarianzen noch miteinander vergleichen?
> > Für Teilaufgabe 3. c) sollten wir aber eher nominale Zusammenhangsmaße anwenden, wie z.B Chi-Quadrat oder Phi-Koeffizient meint ihr nicht?

Ich habe jetzt eine Funktion für Chi-Quadrat Koeffizienten, Pearsons Kontingenzindex und korrigierten Person Index geschrieben. Damit sollte man die Zusammenhänge zwischen kategorialen Variablen betrachten können.
