### ISSUE TITLE
Step 

### ISSUE THREAD

**Issue by JuliaKeiter** [Ketii/GruppenarbeitWA2021#2]
Ich denke wir sind jetzt bei 4. angekommen. wollen wir drei den 4. Schritt parallel machen oder sollen wir das aufteilen? @aliciahemmersbach @Kaya0110

**Comment by Kaya0110** [comment]
Ich fände parallel ganz gut, dann kann man bei Fragen nochmal besser die anderen fragen. Oder wie seht ihr das? @aliciahemmersbach @JuliaKeiter

**Comment by aliciahemmersbach** [comment]
> Ich fände parallel ganz gut, dann kann man bei Fragen nochmal besser die anderen fragen. Oder wie seht ihr das? @aliciahemmersbach @JuliaKeiter

Find ich auch gut, aber die Aufgabe würd ich schon aufteilen oder?
Wir könnten das ja entweder nach den Variablen aufteilen, oder so, dass eine die deskriptive Auswertung macht, eine die bivariate und eine die Visualisierung?
@JuliaKeiter @Kaya0110

**Comment by JuliaKeiter** [comment]
find ich gut, also eine a) und b), eine c) und d) und eine e) und f) richtig?

**Comment by Kaya0110** [comment]
> 
> 
> find ich gut, also eine a) und b), eine c) und d) und eine e) und f) richtig?
 Ja hört sich gut an. Soll ich dann einfach a und b machen oder möche das wer anders lieber machen?

**Comment by aliciahemmersbach** [comment]
> find ich gut, also eine a) und b), eine c) und d) und eine e) und f) richtig?

ja genau



> > find ich gut, also eine a) und b), eine c) und d) und eine e) und f) richtig?
> > Ja hört sich gut an. Soll ich dann einfach a und b machen oder möche das wer anders lieber machen?

ich würd dann c und d machen, wenn das in Ordnung ist

**Comment by JuliaKeiter** [comment]
ja klar, dann mach ich a) und b) ok?

**Comment by JuliaKeiter** [comment]
okay, dann mach ich e) und f)

**Comment by Kaya0110** [comment]
> 
> 
> okay, dann mach ich e) und f)

Okay
