### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by aliciahemmersbach** [Ketii/GruppenarbeitWA2021#3]
Mir ist gerade aufgefallen, dass ich mich bei der Funktion2 mit dem Modalwert vertan habe. Ich ändere das mal eben, dann muss aber die Funktion nochmal ausgeführt werden bei @Kaya0110 s Aufgabe

**Comment by Kaya0110** [comment]
Alles klar

**Comment by aliciahemmersbach** [comment]
ist geändert!

**Comment by Kaya0110** [comment]
Habs jz auch bei mir geändert
