### ISSUE TITLE
Auswertung fehlt

### ISSUE THREAD

**Issue by Ketii** [Ketii/GruppenarbeitWA2021#4]
Mir ist aufgefallen dass du Mathe LK nicht auswertest weil es keine metrische Variable ist @Kaya0110 , aber für die Häufigkeitstabelle und den Modalwert brauchst du per se keine metrische Variablen, kategorialen kann man auch auswerten, kannst du das vielleicht nochmal versuchen?

**Comment by Kaya0110** [comment]
Ja stimmt, hast Recht
