### ISSUE TITLE
Diskussion Ergbenisse

### ISSUE THREAD

**Issue by Kaya0110** [Ketii/GruppenarbeitWA2021#5]

**Comment by Kaya0110** [comment]
Wir sind ja jz so gut wie fertig mit den Schritten 1-4.  Dann können wir mal mit der Diskussion der Ergebnisse anfangen.

**Comment by JuliaKeiter** [comment]
Ich fang mal mit der Vorstellung meiner Erkenntnisse an: die Quantilsfunktion (Funktion e) ) zeigte mir, dass die meisten Befragten jünger als 26 Jahre alt waren. Die Befragten gaben am häufigsten an, ein sehr hohes Interesse an der Mathematik zu haben, beim Programmieren haben immerhin noch knapp die Hälfte der Befragten ein hohes bis sehr hohes Interesse. 
Die Visualisierungsfunktion (Funktion f)) bestätigte  mir diese Beobachtungen, ich mit ihr aber auch herausgefunden, dass der Großteil der Befragten einen Mathe Leistungskurs belegt haben und die Gruppe der Statistik Studierenden am stärksten vertreten war. 

Soo, habt ihr @DanuschaGrosse-Hering , @Ketii diese Ergebnisse auch so vorgesehen?  ':D

**Comment by aliciahemmersbach** [comment]
Zu meinen Ergebnissen:
Für den Zusammenhang zwischen der Wahl des Studienfachs und der Belegung des Mathe Lks ergibt sich ein Kontingenzkoeffizient von 0.2466406 (Pearson) beziehungsweise 0.3488025 (korrigierter Pearson). Das deutet auf einen mäßigen Zusammenhang zwischen den beiden Variablen hin.  Ich denke, dass das vor allem daran liegt, dass der Großteil aller betrachteten Personen sowieso den Mathe Leistungskurs hatte.

**Comment by aliciahemmersbach** [comment]
Für den Zusammenhang zwischen Alter und Belegung des Mathe LKs kommt für den gruppierten Bravais Pearson Korrelationskoeffizienten  0.1230587 heraus. Ich finde aber, dass die Betrachtung inhaltlich nicht besonders viel Sinn macht. Ein leichter Zusammenhang ist wahrscheinlich zufällig?

Dann wurde noch der Zusammenhang zwischen dem Interesse an Mathematik bzw. Informatik und der Belegung des Mathe LKs betrachtet, mit einem gruppierten Bravais Pearson Korrelationskoeffizienten von 0.02241161 bzw. 0.1222973. 
Ich glaube, dass die Funktion hier nicht so sinnvoll ist, weil ja die Skala für das Interesse jeweils nur in zwei Gruppen geteilt wird.

**Comment by DanuschaGrosse-Hering** [comment]
> Ich fang mal mit der Vorstellung meiner Erkenntnisse an: die Quantilsfunktion (Funktion e) ) zeigte mir, dass die meisten Befragten jünger als 26 Jahre alt waren. Die Befragten gaben am häufigsten an, ein sehr hohes Interesse an der Mathematik zu haben, beim Programmieren haben immerhin noch knapp die Hälfte der Befragten ein hohes bis sehr hohes Interesse.
> Die Visualisierungsfunktion (Funktion f)) bestätigte mir diese Beobachtungen, ich mit ihr aber auch herausgefunden, dass der Großteil der Befragten einen Mathe Leistungskurs belegt haben und die Gruppe der Statistik Studierenden am stärksten vertreten war.
> 
> Soo, habt ihr @DanuschaGrosse-Hering , @Ketii diese Ergebnisse auch so vorgesehen? ':D

 Also das Alter der Befragten sollte im Mittel 25 Jahre sein, das passt ja dann schonmal recht gut, das e natürlich auch eine Abweichung gibt.  Die meisten der Befragten sollten auch Statistik studieren .  Wir haben da Interesse an Mathematik bzw. am Programmieren an dem Studiengang gekoppelt.  Menschen die Mathe studieren haben logischerweise ein höheres Interesse an Mathematik als Informatikstudierende. Da die Statistik studierenden häufiger repräsentiert werden sollten,  und wir diesen auch ein relativ hohes Interesse an Mathe gesetzt haben, passt dieses Ergebnis auch gut.  Wir haben die Wahrscheinlichkeit, das jemand einen Mathe Leistungskurs hatte auf  zwischen 55% und  90% gesetzt, dies spiegelt sich auch in den Ergebnissen wieder.

**Comment by DanuschaGrosse-Hering** [comment]
> Zu meinen Ergebnissen:
> Für den Zusammenhang zwischen der Wahl des Studienfachs und der Belegung des Mathe Lks ergibt sich ein Kontingenzkoeffizient von 0.2466406 (Pearson) beziehungsweise 0.3488025 (korrigierter Pearson). Das deutet auf einen mäßigen Zusammenhang zwischen den beiden Variablen hin. Ich denke, dass das vor allem daran liegt, dass der Großteil aller betrachteten Personen sowieso den Mathe Leistungskurs hatte.

 Okay,  wir haben da eigentlich schon einen Zusammenhang erstellt also die Wahrscheinlichkeit, dass ein:e Mathematikstudent:in einen Matheleistungskurs hatte war größer als die einer:s Informatikstudent:in. Aber vielleicht unterschieden sich die W'keiten nicht stark genug, bzw. die Stichprobe war nicht groß genug, um dies auch abzubilden.

**Comment by Ketii** [comment]
> Für den Zusammenhang zwischen Alter und Belegung des Mathe LKs kommt für den gruppierten Bravais Pearson Korrelationskoeffizienten 0.1230587 heraus. Ich finde aber, dass die Betrachtung inhaltlich nicht besonders viel Sinn macht. Ein leichter Zusammenhang ist wahrscheinlich zufällig?
> 
> Dann wurde noch der Zusammenhang zwischen dem Interesse an Mathematik bzw. Informatik und der Belegung des Mathe LKs betrachtet, mit einem gruppierten Bravais Pearson Korrelationskoeffizienten von 0.02241161 bzw. 0.1222973.
> Ich glaube, dass die Funktion hier nicht so sinnvoll ist, weil ja die Skala für das Interesse jeweils nur in zwei Gruppen geteilt wird.

Wir haben zwischen Alter und Belegung des Mathe LKs und zwischen dem Interesse an Mathe bzw. Informatik und Mathe LK  keinen Zusammenhang erstellt, der leichte Zusammenhang ist daher völliger Zufall.

**Comment by Kaya0110** [comment]
Dann stelle ich mal meine Ergebnisse vor: Meine Ergebnisse zeigen auch, dass die Befragten recht jung waren, ca. 25 Jahre im arithmetischen Mittel. Die Daten streuen auch rech gering um diesen Mittelwert, da die Standardabweichung nur 2,27 beträgt. 
Gerenell ist sowohl ein recht hohes Interesse an Mathematik als auch an Programmieren, wobei das Interesse an Mathe noch etwas höher ist mit 5,73.

**Comment by Kaya0110** [comment]
> 
> 
> Dann stelle ich mal meine Ergebnisse vor: Meine Ergebnisse zeigen auch, dass die Befragten recht jung waren, ca. 25 Jahre im arithmetischen Mittel. Die Daten streuen auch rech gering um diesen Mittelwert, da die Standardabweichung nur 2,27 beträgt.
> Gerenell ist sowohl ein recht hohes Interesse an Mathematik als auch an Programmieren, wobei das Interesse an Mathe noch etwas höher ist mit 5,73.

Das passt ja schonmal gut zu dem was @JuliaKeiter und @DanuschaGrosse-Hering schon gesagt haben

**Comment by Kaya0110** [comment]
Die Häufigkeitstabellen und Mdalwerte geben auch keine bedeutenden zusätzlichen Informationen mehr, außer dass 81 der 100 Personen Mathe-LK hatten

**Comment by Ketii** [comment]
> > Zu meinen Ergebnissen:
> > Für den Zusammenhang zwischen der Wahl des Studienfachs und der Belegung des Mathe Lks ergibt sich ein Kontingenzkoeffizient von 0.2466406 (Pearson) beziehungsweise 0.3488025 (korrigierter Pearson). Das deutet auf einen mäßigen Zusammenhang zwischen den beiden Variablen hin. Ich denke, dass das vor allem daran liegt, dass der Großteil aller betrachteten Personen sowieso den Mathe Leistungskurs hatte.
> 
> Okay, wir haben da eigentlich schon einen Zusammenhang erstellt also die Wahrscheinlichkeit, dass ein:e Mathematikstudent:in einen Matheleistungskurs hatte war größer als die einer:s Informatikstudent:in. Aber vielleicht unterschieden sich die W'keiten nicht stark genug, bzw. die Stichprobe war nicht groß genug, um dies auch abzubilden.

Ja ich glaube auch dass die Stichprobengrößen da eine Rolle spielen können.

**Comment by Kaya0110** [comment]
> 
> 
> > > Zu meinen Ergebnissen:
> > > Für den Zusammenhang zwischen der Wahl des Studienfachs und der Belegung des Mathe Lks ergibt sich ein Kontingenzkoeffizient von 0.2466406 (Pearson) beziehungsweise 0.3488025 (korrigierter Pearson). Das deutet auf einen mäßigen Zusammenhang zwischen den beiden Variablen hin. Ich denke, dass das vor allem daran liegt, dass der Großteil aller betrachteten Personen sowieso den Mathe Leistungskurs hatte.
> > 
> > 
> > Okay, wir haben da eigentlich schon einen Zusammenhang erstellt also die Wahrscheinlichkeit, dass ein:e Mathematikstudent:in einen Matheleistungskurs hatte war größer als die einer:s Informatikstudent:in. Aber vielleicht unterschieden sich die W'keiten nicht stark genug, bzw. die Stichprobe war nicht groß genug, um dies auch abzubilden.
> 
> Ja ich glaube auch dass die Stichprobengrößen da eine Rolle spielen können.

Dem würde ich auch zustimmen

**Comment by JuliaKeiter** [comment]
das ist ja häufig das Problem

**Comment by Ketii** [comment]
> > Dann stelle ich mal meine Ergebnisse vor: Meine Ergebnisse zeigen auch, dass die Befragten recht jung waren, ca. 25 Jahre im arithmetischen Mittel. Die Daten streuen auch rech gering um diesen Mittelwert, da die Standardabweichung nur 2,27 beträgt.
> > Gerenell ist sowohl ein recht hohes Interesse an Mathematik als auch an Programmieren, wobei das Interesse an Mathe noch etwas höher ist mit 5,73.
> 
> Das passt ja schonmal gut zu dem was @JuliaKeiter und @DanuschaGrosse-Hering schon gesagt haben

Ja die Ergebnisse passen recht gut,  die Standardabweichung sollte auch  2 sein. Und leicht höheres Interesse an Mathematik war auch so gewollt.

**Comment by aliciahemmersbach** [comment]
Wollen wir die Ergebnisse der Auswertung bzw. der Diskussion vielleicht in einer Rmarkdown Datei zusammenfassen? Dann ist einmal alles beisammen.

@JuliaKeiter @DanuschaGrosse-Hering @Ketii @Kaya0110

**Comment by JuliaKeiter** [comment]
@Ketii hast du das respository für Marie schon freigeschaltet?

**Comment by Ketii** [comment]
> @Ketii hast du das respository für Marie schon freigeschaltet?

Es ist ein öffentliches Repository, jeder kann es sehen, wir müssen nur den Link teilen.
